### ISSUE TITLE
Display error message if WebGPU not working

### ISSUE THREAD

**Issue by jamesscottbrown** [harp-lab/GraphWaGu#1]
I tried using the live demo (https://harp-lab.github.io/GraphWaGu/), and spent a while trying to determine why it wasn't working for me.

The `componentDidMount` method in `Page.tsx` requests a GPU adapter. If this fails, then `adapter` is `null`, and the console logs `Uncaught TypeError: Cannot read properties of null` whenever the user tries to do anything.

It would be more helpful if the page detected if `adapter` or `device` is null, and displayed a message saying something like "GraphWaGu requires WebGPU, which is not currently enabled. You may be using an incompatible web browser or hardware, or have this feature disabled. If you are using Chrome, enable the setting at chrome://flags/#enable-unsafe-webgpu. If you are using Safari, first enable the Developer Menu (Preferences > Advanced), then check Develop > Experimental Features > WebGPU."

(I saw the paper on the EuroVis program, and searching for the title brought me to Will Usher's personal site, which liked to the GitHub repo and demo )

**Comment by ldyken53** [comment]
Fixed [here](https://github.com/harp-lab/GraphWaGu/commit/6881990f0dcf825ce91d3cb6dd69f2a009cc39c3).

Added checks for WebGPU compatibility and alert with your message if checks fail.

Thanks!
