### ISSUE TITLE
live demo isn't working due to webgpu api has changed

### ISSUE THREAD

**Issue by quarksb** [harp-lab/GraphWaGu#5]
please review this [pull request](https://github.com/harp-lab/GraphWaGu/pull/4) if you have time

**Comment by quarksb** [comment]
I am sure live demo didn't work anymore(both in chrome and edge), since API  has changed, there is not "getPreferredFormat()" func

**Comment by ldyken53** [comment]
Thank you for your code, I finally have some free time, so I've merged your changes into a refactor branch. I plan on making a few changes to the repo this week with respect to the GPU algorithm, then merging this refactor into main.
